import os
import json
from datetime import datetime

# -----------------------
# 🌐 SEARCH IMPORT
# -----------------------
try:
    from ddgs import DDGS
except ImportError:
    DDGS = None

# -----------------------
# 🌐 SCRAPER IMPORT
# -----------------------
import requests
from bs4 import BeautifulSoup


# -----------------------
# 🛠 MAIN TOOL ROUTER
# -----------------------
def run_tool(action):
    act = action.get("action")
    inp = action.get("input")

    os.makedirs("workspace", exist_ok=True)

    # -----------------------
    # ✍️ WRITE
    # -----------------------
    if act == "write":
        return f"Generated content:\n{str(inp)}"

    # -----------------------
    # 🧠 ANALYZE
    # -----------------------
    elif act == "analyze":
        return f"Analysis:\n{str(inp)}"

    # -----------------------
    # 🌐 SEARCH
    # -----------------------
    elif act == "search":
        if DDGS is None:
            return "Search tool not installed. Run: pip install ddgs"

        try:
            query = str(inp).strip()

            if len(query.split()) < 4:
                query += " detailed explanation examples trends"

            results_text = []

            with DDGS() as ddgs:
                results = ddgs.text(query, max_results=5)

                for r in results:
                    results_text.append(
                        f"{r.get('title')}\n{r.get('href')}\n{r.get('body')}"
                    )

            if not results_text:
                return f"No strong results found.\nRefined query: {query}"

            return "Search results:\n\n" + "\n\n---\n\n".join(results_text)

        except Exception as e:
            return f"Search error: {str(e)}"

    # -----------------------
    # 🕷️ SCRAPE 🔥🔥
    # -----------------------
    elif act == "scrape":
        try:
            url = str(inp).strip()

            headers = {
                "User-Agent": "Mozilla/5.0"
            }

            response = requests.get(url, headers=headers, timeout=10)

            if response.status_code != 200:
                return f"Failed to fetch page: {response.status_code}"

            soup = BeautifulSoup(response.text, "html.parser")

            # Remove junk
            for tag in soup(["script", "style", "nav", "footer", "header"]):
                tag.extract()

            text = soup.get_text(separator="\n")

            # Clean lines
            lines = [line.strip() for line in text.splitlines() if line.strip()]
            clean_text = "\n".join(lines)

            # 🔥 LIMIT SIZE (VERY IMPORTANT)
            clean_text = clean_text[:4000]

            return f"Scraped content from {url}:\n\n{clean_text}"

        except Exception as e:
            return f"Scrape error: {str(e)}"

    # -----------------------
    # 📁 SAVE FILE
    # -----------------------
    elif act == "save_file":
        try:
            safe_name = str(inp)[:50].replace(" ", "_").replace("/", "_")
            filename = f"{safe_name}.txt"
            filepath = os.path.join("workspace", filename)

            content = f"""Generated by agent
Time: {datetime.now()}

Content:
{str(inp)}
"""

            with open(filepath, "w") as f:
                f.write(content)

            return f"File saved: {filepath}"

        except Exception as e:
            return f"File error: {str(e)}"

    # -----------------------
    # 📁 STRUCTURED SAVE
    # -----------------------
    elif act == "save_structured":
        try:
            filename = f"structured_{int(datetime.now().timestamp())}.txt"
            filepath = os.path.join("workspace", filename)

            if isinstance(inp, (dict, list)):
                content = json.dumps(inp, indent=2)
            else:
                content = str(inp)

            with open(filepath, "w") as f:
                f.write(content)

            return f"Structured file saved: {filepath}"

        except Exception as e:
            return f"File error: {str(e)}"

    return f"Unknown action: {act}"

