import os
from datetime import datetime

try:
    from duckduckgo_search import DDGS
except ImportError:
    DDGS = None


def run_tool(action):
    act = action.get("action")
    inp = action.get("input")

    os.makedirs("workspace", exist_ok=True)

    # -----------------------
    # ✍️ WRITE (basic)
    # -----------------------
    if act == "write":
        return f"Generated content: {inp}"

    # -----------------------
    # 🧠 ANALYZE
    # -----------------------
    elif act == "analyze":
        return f"Analysis: {inp}"

    # -----------------------
    # 🌐 SEARCH (real)
    # -----------------------
    elif act == "search":
        if DDGS is None:
            return "Search tool not installed."

        try:
            results_text = []

            with DDGS() as ddgs:
                results = ddgs.text(inp, max_results=5)

                for r in results:
                    results_text.append(
                        f"{r['title']}\n{r['href']}\n{r['body']}"
                    )

            return "Search results:\n\n" + "\n\n---\n\n".join(results_text)

        except Exception as e:
            return f"Search error: {str(e)}"

    # -----------------------
    # 📁 FILE WRITER 🔥
    # -----------------------
    elif act == "save_file":
        try:
            filename = f"{inp.replace(' ', '_')}.txt"
            filepath = os.path.join("workspace", filename)

            content = f"""Generated by agent
Time: {datetime.now()}

Content:
{inp}
"""

            with open(filepath, "w") as f:
                f.write(content)

            return f"File saved: {filepath}"

        except Exception as e:
            return f"File error: {str(e)}"

    # -----------------------
    # 📁 ADVANCED FILE WRITE 🔥🔥
    # -----------------------
    elif act == "save_structured":
        try:
            filename = f"structured_{int(datetime.now().timestamp())}.txt"
            filepath = os.path.join("workspace", filename)

            with open(filepath, "w") as f:
                f.write(inp)

            return f"Structured file saved: {filepath}"

        except Exception as e:
            return f"File error: {str(e)}"

    # -----------------------
    return "Unknown action"
